---
# tasks file for apache

- name: Install Apache
  apt:
    name: "{{ apache_package }}"
    state: present
    update_cache: yes

- name: Start and Enable Apache Service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Deploy index.html from Jinja2 Template
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    mode: "0644"
  notify: Restart Apache

