#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx

- name: Install NGINX (Ubuntu/Debian)
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install NGINX (Amazon Linux/RedHat)
  yum:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and Enable NGINX
  service:
    name: nginx
    state: started
  notify: Restart NGINX


