---
- name: first_P
  hosts: localhost
  
  tasks:
    - name: Install Apache
      apt:
        name: 
          - apache2
          - ufw
        state: present
        update_cache: yes

    - name: Start Apache
      service:
        name: apache2
        state: started

    - name: Deploy index.html
      copy:
        content: "<H1> Hello world, this is my first playbook </H1>"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Enable Firewall
      ufw:
        rule: allow
        port: 80
        proto: tcp
