---
- name: Deploy Nginx with Variables & Templates
  hosts: localhost
  become: yes

  vars_files:
    - web_vars.yml

  tasks:
    - name: Install Nginx
      apt:
        name: "{{ package_name }}"
        state: present

    - name: Start nginx
      service:
        name: "{{ service_name }}"
        state: started

    - name: Deploy index.html
      template:
        src: templates/index.html.j2
        dest: "{{ web_root }}/index.html"
        mode: '0644'

    - name: Enable Firewall
      ufw:
        rule: allow
        port: "{{ port_f }}"
        proto: tcp
