name: Deploy Web App with Ansible

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures repo files are available

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
    
      - name: Debug SSH Key
        run: cat ~/.ssh/id_rsa
       
      - name: Ping Servers with Ansible
        run: |
          ansible -i hosts.ini -m ping all

      - name: Deploy Web App
        run: |
          ansible-playbook -i hosts.ini playbooks/install_nginx.yml
