name: Deploy Web App with Ansible

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # This ensures the repo files are available

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          

      - name: Run Ansible Playbook
        run: |
          ls -ltr
          pwd
          ansible-playbook -i hosts.ini playbooks/install_nginx.yml --private-key <(echo "${{ secrets.SSH_PRIVATE_KEY }}") --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"


