name: Deploy Web App with Ansible

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # This ensures the repo files are available

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
          run: |
            eval `ssh-agent -s`
            mkdir -p /home/runner/.ssh/
            touch /home/runner/.ssh/id_rsa
            echo -e "{{secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
            chmod 700 /home/runner/.ssh/id_rsa
      - name: Run Ansible Playbook
        run: |
          ansible -i hosts.ini -m ping all

      - name: Run Ansible Playbook
        run: 
          ansible-playbook -i hosts.ini playbooks/install_nginx.yml
