name: Deploy Web App with Ansible

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/hosts.ini ansible/playbooks/install_nginx.yml --private-key private_key

      - name: Cleanup SSH Key
        run: rm -f private_key  # Ensures the key is removed after execution

          
         
